### PR TITLE
Support multiple root paths

### PR DESCRIPTION
**Pull request by mark-hahn**
I have three different folders containing projects and this aggregates projects from all three.

### CODE REVIEW

**Comment by prrrnd** [comment]
That's a great idea, thanks @mark-hahn. [Tests are failing](https://travis-ci.org/prrrnd/atom-git-projects/builds/51207711) though, would you mind updating them?

**Comment by mark-hahn** [comment]
The tests pass with ctrl-alt-P on my pc.  I don't understand the travis error ...

    The command "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh" exited with 1.

It doesn't seem related to my PR.

**Comment by prrrnd** [comment]
I believe the command exited because the tests failed.
```bash
2 tests, 2 assertions, 1 failure, 0 skipped

Tests failed
```
I'll try to look at it when I have some time. Thanks for your contribution!

**Comment by mark-hahn** [comment]
I'm curious.  What was the problem?  Was it my fault?

**Comment by prrrnd** [comment]
Somehow `rootPath` was `undefined`, causing an error with the `split`. I quickly fixed it with [this commit](https://github.com/prrrnd/atom-git-projects/commit/f3cd7a1307d17ac68901aaf2a561287a02f792aa), but I'm not sure why this happened. I'll have a better look at it when I have some time, hopefully later today. You're welcome to investigate if you have some time :-)

**Comment by mark-hahn** [comment]
> Somehow rootPath was undefined,

You are talking about the tests after my second and final commit, right?

Interesting, I don't know if you noticed but my first commit changed
rootPath to rootPaths.  Then I realized that would screw up existing user's
settings.  So I did a second commit that went back to rootPath.  Maybe I
missed one. I'll check right now. In any case the tests passed on my PC 2/2.

**Pull request merged**
