### PR TITLE
Show recent projects

### PR DESCRIPTION
**Pull request by sberan**
Puts recent projects at the beginning of the list, and shows them while the others are loading!

### CODE REVIEW

**Comment by prrrnd** [comment]
I think it's a good idea, but we should maybe add the possibility to enable/disable this feature in the package settings. It can be confusing to some users as it "breaks" the sort order defined by the other setting.
Also, a small thing – It would be good to remove the trailing semicolons and the unnecessary fat arrows (`=>`)
Thanks again for the awesome work, @sberan !

**Comment by sberan** [comment]
@prrrnd - good idea, I've added a config setting for this. I also removed some semicolons, I didn't notice any extra fat arrows, but I'm pretty new to coffeescript. Let me know if this needs any other changes!

**Comment by prrrnd** [comment]
Hi @sberan . I have actually removed the fat arrows and trailing semicolons yesterday in https://github.com/prrrnd/atom-git-projects/commit/ea2019d1c0dfe4dcc8e5ad05357cb7a2e2e919c7. Sorry I didn't mention it afterwards. I'll have a look at your changes as soon as I have some time :+1:

**Comment by prrrnd** [comment]
Some others idea related to this new feature..
- Possibility to reopen the latest project with a new shortcut
- Possibility to clear the recent projects

Let me know if you're interested in working on those, otherwise I can give it a try later :)

**Comment by prrrnd** [comment]
Hi,
I think we'll go with [this solution](https://github.com/prrrnd/atom-git-projects/pull/44) instead.
Thanks for your work though :+1:

**Pull request closed without merging**
